### ISSUE TITLE
[ENH] Optional을 이용한 존재 유무 검증 로직 제언

### ISSUE THREAD

**Issue by tmddusgood** [Team-PandaN/Team-PandaN-Back#22]

**Comment by implermine** [comment]
저는 단일 객체 호출의 경우에는 Optional<>을 사용하는것이 추천된다고 알고 있습니다.
그러나, 제가 직접 느낀바로는, Optional객체로 감싸는 경우엔, .get()을 사용해야 해당 객체를 불러올 수 있기 때문에,
여러 객체 호출과 단일 객체 호출이 해당 객체를 불러오는 부분이 서로 상이할 수 있다고 생각합니다.
따라서, 저같은 경우에는 Optional을 쓸 것이라면, 단일객체와 다중객체 모두 사용하거나, 혹은 그렇지 않거나 하나의 
정책을 사용하는것이 좋다고 생각합니다

**Comment by mangdo** [comment]
다중 객체 호출이라는 것이 List, Map, Set과 같은 collection이나 array라면
이에 대해서는 Optional을 사용하지 말라고 되어있습니다.

다음 포스팅 중 item17을 읽어보시면 될 것 같습니다.
 https://dzone.com/articles/using-optional-correctly-is-not-optional
