### ISSUE TITLE
[Question] 클라이언트로 전달하는 값들의 자료형 문제

### ISSUE THREAD

**Issue by tmddusgood** [Team-PandaN/Team-PandaN-Back#23]
ex) LocalDate를 굳이 String으로 돌려줘야 하는가?
ex) Step의 경우에는 String으로 주는 것이 맞지 않는가?

**Comment by mangdo** [comment]
JSON의 데이터 타입으로는 다음과 같이 6개만 가능합니다.

1. 숫자(number)
2. 문자열(string)
3. 불리언(boolean)
4. 객체(object)
5. 배열(array)
6. NULL
때문에 이에 맞는 데이터 형식으로 변경하여 반환해야 한다고 생각합니다.

**Comment by mangdo** [comment]
때문에 다음과 같이 코드를 수정하였습니다.
```
@Getter
public class NoteResponseDto {
    private Long noteId;
    private String title;
    private String content;
    private String deadline;
    private String step;

    @Builder
    public NoteResponseDto(Long noteId, String title, String content, LocalDate deadline, Step step) {
        this.noteId = noteId;
        this.title = title;
        this.content = content;
        this.deadline = deadline.toString();
        this.step = step.toString();
    }
}
```
[코드 링크](https://github.com/Team-PandaN/Team-PandaN-Back/blob/develop/src/main/java/com/example/teampandanback/dto/note/response/NoteResponseDto.java)
