### ISSUE TITLE
[Refactoring] ENUM값 수정

### ISSUE THREAD

**Issue by implermine** [Team-PandaN/Team-PandaN-Back#24]
나중에 RDB로 들어갈 내용이긴 하지만, 현 상황으로썬 key와 value로 나누는것이 불필요해보입니다

**Comment by Code-Angler** [comment]
앞선 약속에 맞게 "창고", "할것", "진행중", "끝"과 같은 형태의 value값으로 통신하는 것이 좋다고 생각합니다.

**Comment by Code-Angler** [comment]
저희랑 맞지 않을 수는 있지만, 현재 구현되어 있는 Enum 값의 표현 방법을 능동적으로 쓰기 위한 것에 대한 예시를 첨부합니다. 
https://shinsunyoung.tistory.com/73

**Comment by tmddusgood** [comment]
#74 에서의 MoveStatus와 같은 쓰임새를 예상하고 id 값을 넣었는데, string은 실제로 필요없다고 생각합니다. #74 에서 id 값은 활용되었습니다.
