### ISSUE TITLE
[Question] Note의 ResponseDto에서 deadline 변수의 반환형을 String으로 바꿀 필요가 있습니까?

### ISSUE THREAD

**Issue by Code-Angler** [Team-PandaN/Team-PandaN-Back#34]
현재 Note관련 ResponsDto에서 deadline의 반환 형이 LocalDate 인데, jackson이 json형태로 직렬화 하는 과정에서 string값으로 반환 되는 것으로 보이지만, Back에서는 String을 반환 하는 것이 아니다.
실제로는 LocalDate의 반환 형태는 3개의 value 형태를 가진(Year, Month, Day) 그 안에 값을 포함한 형태이고, Sting 형태로 내려준다면, 각각의 String요소가 인덱싱화 된 하나의 value 형태이다.

반환 형태의 정확한 형태인 String을 내려주는 것이 맞다면,
 앞선 enum 값에 대한 처리와 동일하게 이루어 지면 될 것이라 생각합니다.

https://github.com/Team-PandaN/Team-PandaN-Back/blob/235cd4020919c8aa94ab14517f2c7d1860480790/src/main/java/com/example/teampandanback/dto/note/response/NoteCreateResponseDto.java#L15

**Comment by implermine** [comment]
그렇다면 전반적으로 해당 responseDto 객체의 필드, 생성자 모두 바꿔서
필드의 경우엔,
AS-IS :
private LocalDate deadline;
TO-BE:
private String deadline;

생성자의 경우엔,
AS-IS:
```
 @Builder
    public NoteCreateResponseDto(Long noteId, String title, String content, LocalDate deadline, Step step) {
        this.noteId = noteId.toString();
        this.title = title;
        this.content = content;
        this.deadline = deadline;
        this.step = step.toString();
    }
```
TO-BE:
```
 @Builder
    public NoteCreateResponseDto(Long noteId, String title, String content, LocalDate deadline, Step step) {
        this.noteId = noteId.toString();
        this.title = title;
        this.content = content;
        this.deadline = deadline.toString();
        this.step = step.toString();
    }
```
라고 생각되는데, 제 생각이 맞을까요?

**Comment by Code-Angler** [comment]
사전에 id값의 논의 된 부분이 Long값이라면 
```
@Getter
public class NoteResponseDto {

    private Long noteId;
    private String title;
    private String content;
    private String deadline;
    private String step;

    @Builder
    public NoteResponseDto(Long noteId, String title, String content, LocalDate deadline, Step step) {
        this.noteId = noteId;
        this.title = title;
        this.content = content;
        this.deadline = deadline.toString();
        this.step = step.toString();
   } 
}
```

이러한 형태가 될 것 이라 예상됩니다.
