### ISSUE TITLE
[ENH] DELETE 시에 JOIN 사용하여 두 테이블의 레코드 동시 삭제

### ISSUE THREAD

**Issue by tmddusgood** [Team-PandaN/Team-PandaN-Back#37]
현재로서는 제가 생각한 쿼리는 아래와 같습니다.

DELTE FROM
    테이블1
FROM 
    테이블1 one
INNER JOIN
    테이블2 two
ON 
    two.Project_ID = two.Project_ID
WHERE 
    two.Project_ID = ''

현재 JPA에서는
NoteRepository.deleteby~();
ProjectRepository.deleteby~();
로 쿼리를 2번 날립니다.

쿼리를 이용하면 동시 삭제가 되는지 테스트를 해보겠습니다.

**Comment by mangdo** [comment]
만약 MySQL을 사용하고 있고 두 테이블의 레코드를 동시에 삭제하시고 싶다면 쿼리는 다음과 같이 변경되어야 합니다.
```sql
DELETE
    one, two
FROM
     테이블1 one
INNER JOIN
    테이블2 two
ON
    two.Project_ID = two.Project_ID
WHERE
    two.Project_ID = ''
```
참고 : https://extbrain.tistory.com/74

하지만 Oracle에서는 delete에서 join을 지원하지 않습니다.
때문에 where절의 서브 쿼리를 사용하여 삭제합니다.


다음과 같은 쿼리가 만들어집니다.
```sql
DELETE
FROM
     테이블1 one
WHERE EXISTS (
    SELECT 1
    FROM 테이블2 two
    WHERE two.Project_ID = two.Project_ID AND two.Project_ID = ''
)
```

참고 : https://tora-it-kingdom.tistory.com/10
 https://soniccho.tistory.com/entry/ORACLE-%EC%A1%B0%EC%9D%B8%EC%9C%BC%EB%A1%9C-%EC%82%AD%EC%A0%9C%ED%95%98%EA%B8%B0
 
 하지만 해당 쿼리는 delete시에 join을 사용하는 쿼리에 불가합니다. delete시에 두 테이블의 레코드 동시 삭제하는 쿼리가 아닙니다. Oracle에서는 해당 기능이 제공되고 있지 않는 것 같습니다.

**Comment by mangdo** [comment]
"두 테이블의 레코드 동시 삭제" 라는 기능은 MySQL에는 있고 Oracle에는 없는 기능입니다.
JPQL은 SQL을 추상화해서 특정 데이터베이스 SQL에 의존하지 않습니다. 즉 공통 문법이 아닌 특정 specific한 DBMS 문법은 네이티브 쿼리 등을 사용하는 등 다른 방식으로 풀어야 합니다. 
 
 JPQL위에서 동작하는 Querydsl 역시 해당 기능을 제공하지 않습니다. 
<img src="https://user-images.githubusercontent.com/70243735/128602724-95d8bc5e-d9d4-42cf-ac9e-53aa6529e5df.png" width="400">

두 테이블을 Join시켜 delete하는 쿼리 역시 따로 Querydsl에서 지원하지는 않습니다.
해당 내용이 [Querydsl Github Issue](https://github.com/querydsl/querydsl/issues/2190)에 올라왔으나 처리되지 않았습니다. 하지만 Oracle 예시처럼 where절 서브 쿼리를 이용하면 가능합니다!

<img src="https://user-images.githubusercontent.com/70243735/128603439-0757033f-95ed-426e-a5b2-a56ccfe8f4f8.png" width="400">


저의 결론을 말씀드리면,
&nbsp; &nbsp; '두 테이블의 레코드 동시 삭제' 라는 기능은 Querydsl에서는 불가능합니다.  네이티브를 사용하는 방법을 시도하거나 지금처럼 두 개의 쿼리로 처리하도록 해야 할 것 같습니다.
&nbsp; &nbsp; 'Join을 이용해서 삭제' 라는 기능을 Querydsl에서 사용하려면 where절 서브 쿼리를 이용해야 합니다. 혹은 네이티브 방법을 시도해야 합니다.

**Comment by mangdo** [comment]
[ Querydsl 사용하여 "Join을 이용해서 삭제"기능 구현 ]

<img src="https://user-images.githubusercontent.com/70243735/128622968-65277251-0a1c-4a73-abe1-ab03ffc44719.png" width="400">

에러발생:
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "         
DELETE FROM BOOKMARK CROSS[*] JOIN NOTE NOTE1_ WHERE PROJECT_ID=?"; 

SQL statement:
/* delete from Bookmark bookmark
where bookmark.note.project.projectId = ?1 */ 

delete from bookmark cross join note note1_ where project_id=? [42000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
