### ISSUE TITLE
[Question] findby와 findALL의 차이는 무엇이며, 우리의 UserProjectMapping 쿼리문에 where이 없는 이유는 무엇입니까?

### ISSUE THREAD

**Issue by tmddusgood** [Team-PandaN/Team-PandaN-Back#39]
findby를 써도 리스트를 잘 반환합니다.
findall을 쓰면 쿼리에 where이 보이지 않습니다. 모두 가져오고 get을 하게 된다는 의견

**Comment by tmddusgood** [comment]
https://www.python2.net/questions-1313309.htm

그렇지 않습니다. findby와 findallby는 정확히 같은 쿼리를 동작시킵니다.

우리가 발견한 문제는 JPQL @query에서 where 없이 질의문을 작성했기 때문입니다.

**Comment by implermine** [comment]
감사합니다. 이해했습니다.
