### ISSUE TITLE
[Question] POST요청 시 RequestDto에 Setter가 필요하지 않은 이유는 무엇입니까? 

### ISSUE THREAD

**Issue by implermine** [Team-PandaN/Team-PandaN-Back#41]
현재 상황 : 빌더패턴에 의해서 위변조 불가로 인해, RequestDto Initializing이 안되고 있음.
안되는 상황의 RequestDto 구조
```
@Getter
public class ProjectInvitedRequestDto {
    private String inviteCode;

    @Builder
    public ProjectInvitedRequestDto(String inviteCode) {
        this.inviteCode = inviteCode;
    }
}
```

**Comment by BlossomWhale** [comment]
빌더패턴 때문이 아니였음. 메소드 존재하면 안됌.

**Comment by BlossomWhale** [comment]
아닌가 생성자만 없어도 되나

**Comment by implermine** [comment]
@POST 요청에서 @RequestBody는 다른 메소드의 HTTP요청과는 조금 다른 경우로 JSON PARSING을 한다.
이때 ObjectMapper를 통해 Json Parsing을 해야하는데,

이 타이밍에, 반드시 기본생성자가 필요하다. 따라서 커스텀 생성자를 requestDto에 넣을 경우엔,
따로 기본 생성자를 넣어줘야한다 (어노테이션이든지, 코드로 넣든지...)

혹은 아예 아무 생성자도 만들지않아, 자바에서 지원하는 기본생성자가 남아있어도 좋다.
