### ISSUE TITLE
[예외처리] NOTE 작성/삭제 시 예외 처리

### ISSUE THREAD

**Issue by implermine** [Team-PandaN/Team-PandaN-Back#43]
NOTE작성시, 해당 프로젝트가 실제로 존재하지 않을 수 있고,

NOTE삭제시, 해당 노트가 실제로 존재하지 않을 수 있습니다.

**Comment by tmddusgood** [comment]
확인했습니다 integrate 테스트 이후 진행하겠습니다.

**Comment by mangdo** [comment]
삭제 시에는 예외 처리가 필요하지 않다고 생각합니다.

사용자가 노트 삭제 요청을 보냈을 때 **이미 노트가 삭제되었다면 사용자가 원했던 요청을 수행한 것**과 똑같기 때문에
애초에 예외를 발생시키지 않아도 된다고 생각합니다.
