### ISSUE TITLE
[기능 구현] 노트 삭제시 연동된 북마크 모두 삭제

### ISSUE THREAD

**Issue by implermine** [Team-PandaN/Team-PandaN-Back#48]
노트 삭제시 연동된 북마크 모두 삭제해야 합니다.

**Comment by mangdo** [comment]
NoteService에서 다음과 같은 코드로 note에 연관된 북마크를 삭제하려고 했습니다.
```java
// Note 삭제
@Transactional
public NoteDeleteResponseDto deleteNote(Long noteId) {
    // 삭제할 Note 조회
    Note note = noteRepository.findById(noteId).orElseThrow(
            () -> new ApiRequestException("이미 삭제된 노트입니다.")
    );

    // Note 에 연관된 북마크 삭제
    bookmarkRepository.deleteByNote(note);

    // Note 삭제
    noteRepository.delete(note);

    return NoteDeleteResponseDto.builder()
            .noteId(noteId)
            .build();
}
```

SpringDataJPA에서 제공하는 deleteByNote()를 사용하려 했으나 해당 코드 실행 시에
하나의 Note에 연관된 북마크가 N개 있을 경우 N개의 쿼리가 나가는 것을 발견하였습니다.
```sql
select
    bookmark0_.seq as seq1_0_,
    bookmark0_.note_id as note_id2_0_,
    bookmark0_.user_id as user_id3_0_ 
from
    bookmark bookmark0_ 
where
    bookmark0_.note_id=?

# 하나의 Note에 연관된 Bookmark가 세 개 있는 상황
delete 
    from
        bookmark 
    where
        seq=?
delete 
    from
        bookmark 
    where
        seq=?
delete 
    from
        bookmark 
    where
        seq=?
```

**Comment by mangdo** [comment]
SpringDataJPA에서 제공하는 deleteByNote()는 deleteByNote()를 수행하기 전에 findByNote()를 수행합니다.
이때 영속성 컨텍스트에 List< bookmark >가 올라오게 되며,
bookmark 엔티티들을 모두 한번에 삭제하는 것이 아닌 
bookmark 엔티티 하나씩 삭제하게 됩니다.

이 때문에 여러 번의 delete쿼리가 발생하고 있었습니다.
만약 쿼리 한번으로 삭제하고 싶다면 JPQL이나 Querydsl로 벌크성 delete문을 작성해야 합니다.

**Comment by mangdo** [comment]
벌크 연산 시 주의 점!
영속성 컨텍스트를 무시하고 바로 DB에 쿼리를 날립니다.
때문에 영속성 컨텍스트와 DB가 달라서 문제가 생길 수 있습니다.

이러한 문제를 방지하기 위해서 벌크연산 후에는 다음과 같이 해주는 것이 좋습니다.
entitymanger.flush(); // 영속성 컨텍스트 변경 내용을 모두 DB에 반영한다.
entitymanger.clear(); // 영속성 컨텍스트 초기화


이때 entitymanger.flush();는 굳이 할 필요가 없습니다.
하이버네이트의 FlushModeType의 Default값이 AUTO이기 때문에 이미 자동으로 flush를 하기 때문입니다.
```
AUTO(Default) : flush가 쿼리 실행 시 발생한다.
COMMIT : flush가 트랜잭션이 commit 될 때 발생한다.
```

**Comment by mangdo** [comment]
entitymanger.clear();를 직접 써주는 것보다 어노테이션을 사용하면 더 간단하게 설정할 수 있습니다.

@Modifying(clearAutomatically = true)라는 어노테이션을 설정하면 됩니다.
@Modifying 이 붙은 해당 쿼리 메서드 실행 직후, 영속성 컨텍스트를 clear 할 것 인지를 지정하는 Attribute 입니다. default 값은 false 입니다.

**Comment by yongjae-kim-dev** [comment]
> SpringDataJPA에서 제공하는 deleteByNote()는 deleteByNote()를 수행하기 전에 findByNote()를 수행합니다.
> 이때 영속성 컨텍스트에 List가 올라오게 되며,
> bookmark 엔티티들을 모두 한번에 삭제하는 것이 아닌
> bookmark 엔티티 하나씩 삭제하게 됩니다.
> 
> 이 때문에 여러 번의 delete쿼리가 발생하고 있었습니다.
> 만약 쿼리 한번으로 삭제하고 싶다면 JPQL이나 Querydsl로 벌크성 delete문을 작성해야 합니다.

왜 deleteByNote를 수행하기 전에 findByNote()를 먼저 수행할까요
