### ISSUE TITLE
자바 오픈소스 로깅 라이브러리 SLF4J

### ISSUE THREAD

**Issue by yongjae-kim-dev** [Team-PandaN/Team-PandaN-Back#66]
https://github.com/Team-PandaN/Team-PandaN-Back/blob/bb97c06bf44438fffd6a34d72c2688f31abeabc6/src/main/java/com/example/teampandanback/service/ProjectService.java#L211

SLF4J 엄청 쉽고 강력합니다.
실수로 남겨두신 코드 같기는 하지만 System.out.print 명령어는 생각보다 비용이 비쌉니다

**Comment by Code-Angler** [comment]
네 실수입니다. 감사합니다. 커밋 전에 주의 해야겠네요
