### ISSUE TITLE
Optional isPresent 지양 

### ISSUE THREAD

**Issue by yongjae-kim-dev** [Team-PandaN/Team-PandaN-Back#68]
https://github.com/Team-PandaN/Team-PandaN-Back/blob/bb97c06bf44438fffd6a34d72c2688f31abeabc6/src/main/java/com/example/teampandanback/service/BookmarkService.java#L60

bookmark.ifPresent(bookmarkRepository::delete) 같은 형식은 어떨까요

isPresent + get 조합은 Optional을 쓰는 의미가 줄어듭니다

**Comment by implermine** [comment]
isPresent + get 조합은 Optional을 쓰는 의미가 줄어듭니다

라는 의미는 이해가 되나, 내부 로직에서 bookmark가 null이 아니라면,
이라하고, delete를 수행하는 것 외에도 여러 로직을 담아야된다면 어떻게 해야되나요?

**Comment by yongjae-kim-dev** [comment]
대댓글 어떻게 다나요

**Comment by yongjae-kim-dev** [comment]
ifPresent는 랩핑된 객체가 null이 아닐경우에만 수행됩니다.

null일때는 아무런 동작도 하지 않아요

**Comment by yongjae-kim-dev** [comment]
delete를 수행하는 것 외에도 여러 로직을 담아야된다면 어떻게 해야되나요?
`bookmark.ifPresent(b->{`
 `    bookmarkRepository.delete(b);`
`     BookmarkBackupEntity backupEntity = BookmarkBackupEntity.from(b);`
`     bookmarkBackupRepository.save(backupEntity);`
`});`

같은 방법도 있구요

`bookmark.ifPresent(this::deleteBookmarkWithBackup);`


`private void deleteBookmarkWithBackup(Bookmark bookmark) {`
`     bookmarkRepository.delete(b);`
`     BookmarkBackupEntity backupEntity = BookmarkBackupEntity.from(b);`
`     bookmarkBackupRepository.save(backupEntity);`
`}`


처럼 별도의 메소드로 빼는 방법도 있겠네요
