### ISSUE TITLE
Boolean과 boolean의 Accessor

### ISSUE THREAD

**Issue by yongjae-kim-dev** [Team-PandaN/Team-PandaN-Back#70]
https://github.com/Team-PandaN/Team-PandaN-Back/blob/bb97c06bf44438fffd6a34d72c2688f31abeabc6/src/main/java/com/example/teampandanback/dto/project/ProjectDetailResponseDto.java#L16 

`public Boolean isUpdatableAndDeletable;`
   
Boolean의 경우 Lombok이 앞에 get~을 달아서 만들어지는 메소드가 getIsUpdatableAndDeletable() 입니다.

getter 메소드명이 달라지긴 하지만

`public boolean updateableAndDeletable`

으로 선언하시면 Lombok이 예쁘게

`isUpdateAbleAndDeletable()` 

요렇게 만들어 줍니다

**Comment by mangdo** [comment]
boolean으로 하게 되면 JSON으로 변환하면서 변수명이 달라지는 이슈가 있었습니다
자세한 내용은 노션에서 확인해주세요!
https://www.notion.so/boolean-is-c9c38fe9d8684381ae096cecb9f2f173

**Comment by yongjae-kim-dev** [comment]
답변 감사합니다.

jackson의 직렬화 전략에서 get과 is를 단순 Accessor로 해석해 없어지는 이슈 확인했습니다.

단순 클라이언트에게 응답할 때 필드명이 바뀌는 이슈라면 `@JsonProperty("isUpdateAbleAndDeletable")` 어노테이션을 추가해서 해결할 수 있을 것 같아요. (저 어노테이션에 is로 시작해도 남아있는지는 안해봤음. 근데 될 것 같은 기분)

boolean을 반환하는 메소드는 get보다 is로 만드는게 좀 더 직관적이여서 코멘트 남겼습니다.
(Optional의 isPresent / String의 isBlank / List의 isEmpty )

포스팅 깔끔하네요 잘보겠습니다b

**Comment by mangdo** [comment]
`@JsonProperty("isUpdateAbleAndDeletable")` 시도해봤는데 가능합니다!
당시에는 lombok의 `@getter`로 만드는 함수가 is로 시작하는 것이 이상하다고 생각했었는데,
들어주신 예시를 보니 is로 만드는게 더 자연스럽다는 생각이 듭니다!
수정에 반영하겠습니다!

답변 너무 감사합니다:)
