### ISSUE TITLE
[ENH] 칸반 노트 순서 연결리스트 구현

### ISSUE THREAD

**Issue by implermine** [Team-PandaN/Team-PandaN-Back#74]
프론트와 논의하시죠..

**Comment by tmddusgood** [comment]
![image](https://user-images.githubusercontent.com/39071543/129973816-396dd593-19b8-4062-bc59-fb5e14939609.png)
![image](https://user-images.githubusercontent.com/39071543/129973993-e32b7403-4afd-4e13-92f1-f481f613b9ff.png)


1. Front에게 받은 칸반 노트 5개의 연결 상태가 DB와 같다.
    1. From 상황과 To 상황을 정한다.
    2. 4개의 상황 중 어떤 상황에서 오는가?
        1. originPre와 originNext를 이어준다
            1. Unique: 
                1. 아무것도 실행하지 않음
            2. currentTop: 
                1. originPre.nextId = 0L
            3. currentBottom: 
                1. originNext.previousId = 0L
            4. currentBetween: 
                1. [originPre.next](http://originpre.next) = originNext.id
                2. originNext.pre = originPre.id
    3. 4개의 상황 중 어떤 상황으로 가는가?
        1. goalPre와 goalNext 사이에 current를 넣는다.
            1. Unique:  
                1. current.pre = 0L
                2. [current.next](http://current.next) = 0L
            2. currentTop: 
                1. [goalPre.next](http://goalpre.next) = current.id
                2. current.pre = goalPre.id, 
                3. [current.next](http://current.next) = 0L
            3. currentBottom: 
                1. current.Pre = 0L
                2. [current.Next](http://current.Next) = goalNext.id
                3. goalNext.Pre = current.Id
            4. currentBetween: 서로 연결
                1. [goalPre.Next](http://goalpre.Next) = current.Id
                2. current.pre = goalPre.id
                3. [current.next](http://current.next) = goalNext.id
                4. goalNext.pre = current.id
    4. 스텝 업데이트 (dynamicUpdate라서 공통 실행해도 괜찮다)
2. Front에게 받은 5개의 연결 상태가 DB와 다르다.
    1. 예외를 반환한다.

의 로직으로 칸반형 조회에서 노트를 이동하는 것으로 하겠습니다.
